name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # - cron:  '0 14 * * *'
    - cron:  '40 23 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Tweet
      if: github.event_name == 'schedule'
      env:
        QUANTOFALTA_APPSECRET: ${{ secrets.QUANTOFALTA_APPSECRET }}
        QUANTOFALTA_USERSECRET: ${{ secrets.QUANTOFALTA_USERSECRET }}
        RUST_LOG: quantofalta=debug
      run: ./target/release/quantofalta
    - name: Generate HTML Only
      if: github.event_name != 'schedule'
      env:
        RUST_LOG: quantofalta=debug
      run: ./target/release/quantofalta -n
    - name: Publish HTML
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
          branch: gh-pages
          folder: html
